### ISSUE TITLE
Android Dev.Drewhamilton.Poko.PokoAnnotations bug

### ISSUE THREAD

**Issue by Kebechet** [tuyen-vuduc/dotnet-binding-utils#90]
I am not able to build my library after implementing your nuget: `Dev.Drewhamilton.Poko.PokoAnnotation`
```
System.IO.FileNotFoundException: Could not find file 'C:\Users\samos/.gradle/caches/modules-2/files-2.1/dev.drewhamilton.poko/poko-annotations-jvm/0.15.2/9ad5e5b81d14caf06f29140e6f32ea06a41497b3/poko-annotations-jvm-0.15.2.jar'.
File name: 'C:\Users\samos/.gradle/caches/modules-2/files-2.1/dev.drewhamilton.poko/poko-annotations-jvm/0.15.2/9ad5e5b81d14caf06f29140e6f32ea06a41497b3/poko-annotations-jvm-0.15.2.jar'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Xamarin.Android.Tasks.MonoAndroidHelper.SizeAndContentFileComparer.GetHashCode(FileInfo obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xamarin.Android.Tasks.CheckDuplicateJavaLibraries.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
```

**Comment by tuyen-vuduc** [comment]
@Kebechet what were you trying to achieve?

**Comment by tuyen-vuduc** [comment]
because my approach is to leverage Gradle to resolved the dependencies.

**Comment by Kebechet** [comment]
@tuyen-vuduc I downloaded the latest version and everything seems to work now. Thank you for maintaining this package! ❤️

<img width="900" height="426" alt="Image" src="https://github.com/user-attachments/assets/f3f83910-94fb-4207-acf7-fdbc794c2fb5" />
